[book]
authors = [
    "Anja Strunk",
    "Jonas Sch√§fer",
    "Olivier de Jonckere",
    "Paul Seidler",
    "Steve Starke",
    "Yannic Ahrens"
]
language = "en"
multilingual = false
src = "src"
title = "Yaook Kubernetes Handbook"

# https://crates.io/crates/mdbook-linkcheck
[output.linkcheck]
